sudo: true
dist: trusty

language: python
python:
  - "3.4"

before_install:
  - ./.travis/install-dependencies.sh  

script:
  - ./functional_tests/tcga_rppa_sig-test.sh -p tcga_rppa_sig -d functional_tests/test_data
  - ./.travis/unit-test.sh
